---
# mounting a persistent disk on compute nodes
- name: create data mount point
  sudo: yes
  file: path={{ mount_point }} state=directory
- name: mount the exported data directory
  sudo: yes
  action: mount name={{ mount_point }} src=frontend001:{{ mount_point }} fstype=nfs opts=rw,async,nfsvers=3 state=mounted
