## installing gcsfuse on a debian-based headnode
---
- name: download go binary tarball
  sudo: yes
  get_url: url={{go_url}} dest=/tmp/go{{go_version}}.{{os}}-{{architecture}}.tar.gz
- name: extract go binaries
  sudo: yes
  unarchive: dest=/usr/local
             src=/tmp/go{{go_version}}.{{os}}-{{architecture}}.tar.gz
             copy=no
- name: add go binary to PATH
  sudo: yes
  lineinfile:
    dest=/etc/bash.bashrc
    line="PATH=$PATH:/usr/local/go/bin"
- name: add GOPATH variable to environment
  sudo: yes
  lineinfile:
    dest=/etc/bash.bashrc
    line="GOPATH=$HOME/go"
- name: add binaries made by go to PATH
  sudo: yes
  lineinfile:
    dest=/etc/bash.bashrc
    line="PATH=$GOPATH/bin:$PATH"
- name: get FUSE
  sudo: yes
  apt: name=fuse update_cache=yes
- name: add user to FUSE group
  sudo: yes
  user: name={{user}} group=fuse
- name: set FUSE permissions
  sudo: yes
  file: mode=1660 owner=root group=fuse path=/dev/fuse
- name: install gcsfuse
  script: go_get_gcsfuse.sh 
