---
## mount the local SSD
- name: Create local SSD mount point.
  sudo: yes
  file: path=/mnt/scratch/ state=directory mode=755 owner=nobody group=nogroup
- name: Check if SSD is mounted
  shell: mount -l | grep /dev/sdb | awk '{print $5}'
  register: ssd_is_mounted
- name: Format and mount local SSD.
  sudo: yes
  shell: /usr/share/google/safe_format_and_mount -m "mkfs.ext4 -F" /dev/disk/by-id/google-local-ssd-0 /mnt/scratch/
  when: ssd_is_mounted.stdout != "ext4"
- name: make sure permissions are set
  sudo: yes
  shell: chown -R trubetsk:trubetsk /mnt/scratch/
