# Playbook that attaches a Persistent Disk to a cluster and exports it as an NFS drive on compute nodes of an Elasticluster
---
- hosts: slurm_master
  vars:
    mount_point: /mnt/data/
    persistent_disk: data-thousand-genomes
    zone: us-central1-a
  tasks:
    - name: find gateway IP address
      local_action: shell grep frontend /Users/vasya/.elasticluster/storage/ansible-inventory.gotcloud | cut -d " " -f 2 | cut -f 2 -d "=" 
      register: gateway_ip
    - name: find gateway image
      local_action: shell gcloud compute instances list | grep {{ gateway_ip.stdout }} - | cut -d " " -f 1
      register: gateway_image
    - name: attach persistent disk
      local_action: command gcloud compute instances attach-disk {{ gateway_image.stdout }} --disk={{ persistent_disk }}
    - name: create data mount point
      sudo: yes
      file: path={{ mount_point }} state=directory mode=755 owner=nobody group=nogroup
    - name: format and mount Persistent Disk
      sudo: yes
      shell: /usr/share/google/safe_format_and_mount -m "mkfs.ext4 -F" /dev/sdb {{ mount_point }}
    - name: make sure permissions are set
      sudo: yes
      shell: chown -R trubetsk:trubetsk {{ mount_point }}
    - name: export data mount via NFS
      sudo: yes
      nfsexport: path={{ mount_point }} dest=/etc/exports options=rw,no_root_squash,sync
      notify:
        - restart NFS
  handlers:
    - name: restart NFS
      sudo: yes
      service: name=nfs-kernel-server state=restarted

## create a folder on client
- hosts: slurm_clients
  vars:
    mount_point: /mnt/data/
  tasks:
    - name: create data mount point
      sudo: yes
      file: path={{ mount_point }} state=directory
    - name: mount the exported data directory 
      sudo: yes
      action: mount name={{ mount_point }} src=frontend001:/mnt/data fstype=nfs opts=rw,sync,nfsvers=3 state=mounted
